[2023-11-26T05:34:28.432+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag1/run_id=manual__2023-11-26T05:30:53.766286+00:00/task_id=LOAD_FCT_OUTCOMES permission to 509
[2023-11-26T05:34:28.463+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag1/run_id=manual__2023-11-26T05:30:53.766286+00:00/task_id=LOAD_FCT_OUTCOMES permission to 509
[2023-11-26T05:34:28.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag1.LOAD_FCT_OUTCOMES manual__2023-11-26T05:30:53.766286+00:00 [queued]>
[2023-11-26T05:34:28.503+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag1.LOAD_FCT_OUTCOMES manual__2023-11-26T05:30:53.766286+00:00 [queued]>
[2023-11-26T05:34:28.504+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-26T05:34:28.652+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): LOAD_FCT_OUTCOMES> on 2023-11-26 05:30:53.766286+00:00
[2023-11-26T05:34:28.659+0000] {standard_task_runner.py:57} INFO - Started process 416 to run task
[2023-11-26T05:34:28.662+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag1', 'LOAD_FCT_OUTCOMES', 'manual__2023-11-26T05:30:53.766286+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/Retry2.py', '--cfg-path', '/tmp/tmpb_egc9ev']
[2023-11-26T05:34:28.664+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask LOAD_FCT_OUTCOMES
[2023-11-26T05:34:28.718+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag1/run_id=manual__2023-11-26T05:30:53.766286+00:00/task_id=LOAD_FCT_OUTCOMES permission to 509
[2023-11-26T05:34:28.722+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag1.LOAD_FCT_OUTCOMES manual__2023-11-26T05:30:53.766286+00:00 [running]> on host 42136bd2bf4d
[2023-11-26T05:34:28.804+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag1' AIRFLOW_CTX_TASK_ID='LOAD_FCT_OUTCOMES' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T05:30:53.766286+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T05:30:53.766286+00:00'
[2023-11-26T05:34:29.960+0000] {logging_mixin.py:154} INFO - Executing Create Table Queries...
[2023-11-26T05:34:30.036+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ExtractTransformLoad_Steps/LoadData.py", line 153, in load_data_to_postgres
    postgres_dataloader.create_table(postgres_connection, table_query)
  File "/opt/airflow/dags/ExtractTransformLoad_Steps/LoadData.py", line 121, in create_table
    cursor.execute(table_query)
psycopg2.errors.UndefinedTable: relation "animaldimension" does not exist

[2023-11-26T05:34:30.056+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag1, task_id=LOAD_FCT_OUTCOMES, execution_date=20231126T053053, start_date=20231126T053428, end_date=20231126T053430
[2023-11-26T05:34:30.071+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task LOAD_FCT_OUTCOMES (relation "animaldimension" does not exist
; 416)
[2023-11-26T05:34:30.083+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T05:34:30.103+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
